snippets:
  # git
  - name: git
    keyword: g
    snippet: git

  # docker
  - name: docker
    keyword: d
    snippet: docker

  - name: docker container
    keyword: c
    snippet: container
    context:
      lbuffer: '^docker\s+'

  - name: docker images
    keyword: i
    snippet: image
    context:
      lbuffer: '^docker\s+'

  - name: docker container logs
    keyword: l
    snippet: logs -f --tail 100
    context:
      lbuffer: '^docker\s+(container\s+)?'

.default-options: &default-options
  --no-sort: true
  --info: inline

.multi-options: &multi-options
  <<: *multi-options
  --multi: true

completions:
  # docker
  - name: docker container logs
    patterns:
      - '^docker\s+(container\s+)?logs\s+'
    sourceCommand: "docker container ls | sed 1d"
    options:
      <<: *default-options
    callback: awk '{print $1}'

  - name: docker container stop
    patterns:
      - '^docker\s+(container\+)?stop\s+'
    sourceCommand: "docker container ls | sed 1d"
    options:
      <<: *multi-options
    callback: "awk '{print $1}'"

  - name: docker container rm
    patterns:
      - '^docker\s+(container\+)?rm\s+'
    sourceCommand: "docker container -a | sed 1d"
    options:
      <<: *multi-options
    callback: "awk '{print $1}'"

  - name: docker image rm
    patterns:
      - '^docker\s+(rmi|image\s+rm)\s+'
    sourceCommand: "docker image ls | sed 1d"
    options:
      <<: *multi-options
    callback: "awk '{print $3}'"
